version: '3'

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: pure_banner.settings
      PYTHONPATH: /app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  django-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: pure_banner.settings
      PYTHONPATH: /app
    command: ["python", "manage.py", "test"]
